#!/usr/bin/with-contenv bash

if [ "${PYTHONPATH}X" != "X" ]; then
	echo "WARNING: IGNORING PYTHONPATH: ${PYTHONPATH}" >&2
fi
unset PYTHONPATH

if [ "${DJANGO_SETTINGS_MODULE}X" != "X" ]; then
	echo "WARNING: IGNORING DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}" >&2
fi
unset DJANGO_SETTINGS_MODULE

cd /app/netbox/netbox || exit

exec \
	s6-setuidgid abc /usr/sbin/uwsgi uwsgi.ini
