#!/usr/bin/with-contenv bash

if [ "${PYTHONPATH}X" != "X" ]; then
	echo "WARNING: IGNORING PYTHONPATH: ${PYTHONPATH}" >&2
fi
export PYTHONPATH=

if [ "${DJANGO_SETTINGS_MODULE}X" != "X" ]; then
	echo "WARNING: IGNORING DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}" >&2
fi
export DJANGO_SETTINGS_MODULE=

mkdir -p /config/scripts

declare -A NETBOX_CONF
NETBOX_CONF[ALLOWED_HOST]=${ALLOWED_HOST:-netbox.example.com}
NETBOX_CONF[BASE_PATH]=${BASE_PATH:-}
NETBOX_CONF[DB_NAME]=${DB_NAME:-netbox}
NETBOX_CONF[DB_USER]=${DB_USER:-root}
NETBOX_CONF[DB_PASSWORD]=${DB_PASSWORD:-}
NETBOX_CONF[DB_HOST]=${DB_HOST:-postgres}
NETBOX_CONF[DB_PORT]=${DB_PORT:-}
NETBOX_CONF[REDIS_HOST]=${REDIS_HOST:-redis}
NETBOX_CONF[REDIS_PORT]=${REDIS_PORT:-6379}
NETBOX_CONF[REDIS_PASSWORD]=${REDIS_PASSWORD:-}

cd /app/netbox/netbox/netbox
NETBOX_CONF[SECRET_KEY]=${SECRET_KEY:-$(python3 ../generate_secret_key.py)}

if [ ! -f "/config/configuration.py" ]; then
	cp /defaults/configuration.py /config/configuration.py

	# sed in values or skip if value not set
	for KEY in "${!NETBOX_CONF[@]}"; do \
		sed -i 's|{{'$KEY'}}|'${NETBOX_CONF[$KEY]}'|g' /config/configuration.py
	done
fi

[[ ! -e "/config/media" ]] && \
	mv /app/netbox/netbox/media /config/media

rm -rf /app/netbox/netbox/media
ln -sf /config/media /app/netbox/netbox/media

ln -sf /config/configuration.py /app/netbox/netbox/netbox/configuration.py

mv /defaults/uwsgi.ini /app/netbox/netbox/uwsgi.ini > /dev/null 2>&1

# permissions
chown -R abc:abc \
	/app/netbox \
	/config

cd /app/netbox || exit

s6-setuidgid abc /usr/bin/python3 netbox/manage.py migrate

if [ -n "$SUPERUSER_EMAIL" ] && [ -n "$SUPERUSER_PASSWORD" ];
then

cat << EOF | s6-setuidgid abc python3 /app/netbox/netbox/manage.py shell
from django.contrib.auth.models import User;
from users.models import Token;

username = 'admin';
password = '$SUPERUSER_PASSWORD';
email = '$SUPERUSER_EMAIL';

if User.objects.filter(username=username).count()==0:
    User.objects.create_superuser(username, email, password);
    print('Superuser created.');
else:
    print('Superuser creation skipped. Already exists.');
EOF


	if [ -n "$SUPERUSER_API_TOKEN" ]
	then

cat << EOF | s6-setuidgid abc python3 /app/netbox/netbox/manage.py shell
from django.contrib.auth.models import User;
from users.models import Token;

username = 'admin';
token = '$SUPERUSER_API_TOKEN';

u=User.objects.get(username=username);
Token.objects.create(user=u, key=token);
print('Superuser API Key added.');

EOF

	fi
fi
